### ISSUE TITLE
Make it compatible with 'Smooth Scroll Everywhere'

### ISSUE THREAD

**Issue by Imzxhir** [hamarb123/MCMacOSInputFixes#8] opened 2023-02-11 11:19 UTC
Description: Currently when both 'MacOS Input Fixes' and 'Smooth Scroll Everywhere' are in the same mods folder / instance, it normally defaults to this mods scroll fix which in my opinion it should not do. Instead when both mods are present in the instance, maybe make it so it uses 'Smooth Scrolling' instead of the fix for MacOS scrolling.

Mod: [Smooth Scrolling Everywhere](https://www.curseforge.com/minecraft/mc-mods/smooth-scrolling-everywhere-fabric)

**Comment by hamarb123** [comment] 2023-02-11 12:15
The issue is that this mod groups scroll events together because otherwise you can have issues with selecting items in your hotbar iirc. I'll look to see about toggling the grouping code when it's in the game itself only, this should fix it for 99% of cases I think (including scrolling on any minecraft options menus for example).

**Comment by hamarb123** [comment] 2023-02-12 00:04
Can you tell me if you're experiencing issues with a mouse or a trackpad? That mod doesn't seem to work well with trackpads at all.

**Comment by hamarb123** [comment] 2023-02-12 03:51
I believe version 1.3 should make this work properly, please let me know if it doesn't and re-open the issue.

**Comment by hamarb123** [comment] 2023-02-12 09:11
You shouldn't need an option to make it work, but you need version 1.3. Have you tried it? What isn't working for you (compared to not having this mod), and is it with mouse or trackpad or both?

**Comment by hamarb123** [comment] 2023-02-12 10:09
Ok, so just to check, you're saying that it doesn't scroll in the mod menu screen (from the mod menu mod), and the controls screen, but it works everywhere else (e.g. hotbar, creative inventory, and video options screen)? Also just confirming you're on 1.19.3. To fix the slowness, try enabling the "momentum scrolling" option in the settings for the mod (which are in the mouse settings menu).

**Comment by hamarb123** [comment] 2023-02-12 10:12
Actually, to fix the slowness, try adjusting the scroll sensitivity option in mouse options (which is a setting from Minecraft, and shouldn't interfere with hotbar scrolling).

**Comment by hamarb123** [comment] 2023-02-12 10:15
Can you please list where you have actually checked, especially if it works on the hotbar as expected (ie. 1 scroll on the mousewheel moves 1 item). Can you also try the scroll sensitivity option to see if that helps with the speed, will worry about smoothness afterwards if that's still an issue.

**Comment by hamarb123** [comment] 2023-02-12 10:21
Please check at least: the hotbar (to see if 1 scroll on the mouse = 1 movement left or right), creative inventory, video options screen, and controls screen. Please check them all with scroll sensitivity = 1 (the default), and with scroll sensitivity = 6 (you can adjust this later if you want).

**Comment by hamarb123** [comment] 2023-02-12 10:48
The scroll sensitivity option should give you fine adjustment how fast Minecraft scrolls through those menus, adjust it to whatever value feels about right. Unless I'm misunderstanding you, you're saying that with scroll sensitivity = 1 feels too slow, and with scroll sensitivity = 6 it feels too fast, if that's correct, just try some other options in between until it feels right. Other than that it should basically be the same as without the mod (ie. MacOS Input Fixes only vs vanilla feels basically the same to me on these sorts of menus).

**Comment by hamarb123** [comment] 2023-02-12 11:05
What does scroll sensitivity feel right in then?

**Comment by hamarb123** [comment] 2023-02-12 11:13
Here's a version with a change I'm testing that I think probably fixes this (which would be under a toggleable option), let me know if it fixes your issue (you'll need to extract the jar file out of the zip).
[macos-input-fixes-1.3.jar.zip](https://github.com/hamarb123/MCMacOSInputFixes/files/10715906/macos-input-fixes-1.3.jar.zip)

**Comment by hamarb123** [comment] 2023-02-12 11:26
Cool, I'll add that as an option in a 1.3.1/1.4 update. I'll do it tomorrow though as it's 10.30pm here already.

**Comment by hamarb123** [comment] 2023-02-13 09:42
I've implemented the feature, along with another feature (tooltips on hover to explain each of the options), but I'll release it sometime tomorrow as I want to do some code refactoring first, and I need to thoroughly check it works on every version.

**Comment by hamarb123** [comment] 2023-02-13 09:49
I wanted to add them before, but it is a bit of a pain due to how I use the one jar for 1.14-1.19.3 (1.14 and 1.15 actually don't have tooltips currently as there isn't an obvious API to me for me to use, I may revisit this in the future though) ([here](https://github.com/hamarb123/MCMacOSInputFixes/commit/269f5a87946d1bdf3143e28de814a4aceeeb3f96)'s the commit if you're interested, probably only ~50 of those lines are for the interface smooth scroll feature, most of which is the same lines basically as other options that need to modify the native code logic; the refactoring I want to do is to de-duplicate some of the class, method, and field resolution and lookup code in there).

**Comment by hamarb123** [comment] 2023-02-13 09:53
No, it just won't have tooltips on 1.14 and 1.15

**Comment by hamarb123** [comment] 2023-02-16 10:26
Fixed in 1.4

**Closed by hamarb123** 2023-02-16 10:26 UTC
